---
before:
  hooks:
    - go mod download
builds:
  - id: main
    ldflags: -s -w -X github.com/Phantas0s/devdash/cmd.current={{.Version}} -X github.com/Phantas0s/devdash/cmd.buildDate={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    env:
      - CGO_ENABLED=0
archives:
  - builds:
      - main
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: x86
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
    # Keep a manual, simpler changelog for now
    skip: true
